#!/bin/sh
# shellcheck disable=SC2086,SC2155
DIR="$(mktemp -td dwarf_"$(basename "$0")"XXXXX)"
ARG="-o offset=auto -o tidy_strategy=swap -o workers=4"
export APPDWARF_CMD="$(basename "$0")"
dwarfs $ARG "$0" "$DIR" 2>/dev/null

"$DIR/AppRun" "$@"
fusermount -uz "$DIR"
rmdir "$DIR"
exit
