#!/bin/sh
# shellcheck disable=SC2086,SC2155
DIR="/tmp/dwarf_$(basename "$0")$(echo "$0" | md5sum | head -c5)"
export APPDWARF_CMD="$(basename "$0")"
if [ ! -d "$DIR" ]; then
    mkdir "$DIR"
    ARG="-o offset=auto -o tidy_strategy=swap -o workers=4"
    dwarfs $ARG "$0" "$DIR" 2>/dev/null
fi

"$DIR/AppRun" "$@"
fusermount -quz "$DIR"
rmdir "$DIR" 2> /dev/null
exit
