#!/bin/sh
if ! echo "$1" | grep / ; then
    "$0" https://raw.githubusercontent.com/AppImage/appimage.github.io/master/apps/"$1".md
    exit $?
fi
if ! echo "$1" | grep https ; then
    set -- "https://github.com/$1"
fi
LINK2="$(echo "$1"/releases | sed 's|github.com|api.github.com/repos|')"
if ! echo "$1" | grep github.com; then
    LINK2="$(curl "$1" | grep -o https.\*releases | sed 's|github.com|api.github.com/repos|')"
fi
LINK3="$(curl "$LINK2" | grep -v arm64 | grep -v armh | grep -om1 https.\*AppImage)"
shift
appdwarf "$LINK3" "$@" 
