#!/bin/bash
if ! grep https <<< "$1"; then
   set -- "https://github.com/$1"
fi
LINK2="$(curl "$1" | grep -o https.\*releases | sed 's|github.com|api.github.com/repos|')"
LINK3="$(curl "$LINK2" | grep -v arm64 | grep -om1 https.\*AppImage)"
appdwarf "${@:2}" -u "$LINK3"
