#!/bin/bash
PATH=$(dirname "$(readlink -f "${0}")")/..:$PATH
DIR=/tmp/appdwarf
mkdir -p $DIR
LINK=https://download-chromium.appspot.com/dl/Linux_x64
curl -L "$LINK" | bsdtar xf - -C$DIR

chmod +x $DIR/chrome-linux/chrome*
mv $DIR/chrome-linux/chrome $DIR/chrome-linux/AppRun

appdwarf $DIR/chrome-linux
mv $DIR/chrome-linux.sh chromium
rm -rf $DIR/chrome-linux
