#!/bin/sh
. "$(dirname "$0")"/appmk
part0

TYPE=Runtime
VER=LTS
while [ $# -gt 0 ]; do
    case "$1" in
        STS | sts )
            VER=STS ;;
        SDK | Sdk | sdk )
            TYPE=Sdk ;;
    esac
    shift
done


LINK=https://dotnetcli.azureedge.net/dotnet/$TYPE
VER=$(curl $LINK/"$VER"/latest.version)
TYPE=$(echo "$TYPE" | tr "[:upper:]" "[:lower:]")
LINK="$LINK/$VER/dotnet-$TYPE-$VER-linux-x64.tar.gz"
ungz
ln -s dotnet "$DIR"/AppRun
part9
