#!/bin/sh
. "$(dirname "$0")"/appmk
part0
LINK=https://dotnetcli.azureedge.net/dotnet/Runtime
VER=$(curl $LINK/STS/latest.version)
LINK="$LINK/$VER/dotnet-runtime-$VER-linux-x64.tar.gz"
ungz
ln -s dotnet "$DIR"/AppRun
part9
