#!/bin/sh
. "$(dirname "$0")"/appmk
part0
APP="$1"
eopkg fc -o "$DIR" "$@"
parallel "unzip -op {} install.tar.xz | tar xJf - -C$DIR" ::: "$DIR"/*.eopkg 
rm "$DIR"/*.eopkg
appb
sed -i 3,5s#/bin#/usr/bin# "$DIR"/AppRun
part9
