#!/bin/sh
. "$(dirname "$0")"/appmk
part0
eopkg fc -o "$DIR" "$@"
parallel "unzip -op {} install.tar.xz | tar xJf - -C$DIR" ::: "$DIR"/*.eopkg 
rm "$DIR"/*.eopkg
appb
sed -i 2,4s#/bin#/usr/bin# "$DIR"/AppRun
appdwarf "$DIR"
mv "$DIR".sh "$1"
rm -rf "$DIR"
