#!/bin/sh
PATH=$(dirname "$(readlink -f "${0}")")/..:$PATH
DIR=/tmp/appdwarf/mp3tag
mkdir -p $DIR
LINK=$(curl -L mp3tag.de/dodownload64.html | awk -F'[="]' /URL/'{print $7}')
aria2c "$LINK" -d $DIR -o exe
7z x -y -o$DIR $DIR/exe

rm $DIR/exe
mv $DIR/Mp3tag.exe $DIR/mp3tag
cp "$(dirname "$(readlink -f "${0}")")"/../AppRun $DIR
sed -i '5s/ / wine /' $DIR/AppRun

appdwarf $DIR
mv $DIR.sh mp3tag
rm -rf $DIR
