#!/bin/sh
# shellcheck source=../appdwarf
SOURCE=1 . "$(which appdwarf)"
LINK=$(curl -L mp3tag.de/dodownload64.html | awk -F'[="]' /URL/'{print $7}')
un7z mp3tag
mv "$DIR"/Mp3tag.exe "$DIR"/mp3tag
appa
sed -i '5s/ / wine /' "$DIR"/AppRun
appmk
