#!/bin/sh
. "$(dirname "$0")"/appmk
part0
LINK=http://musl.cc/x86_64-linux-musl-native.tgz
ungz
mv "$DIR"/x86_64-linux-musl-native/* "$DIR"
ln -s gcc "$DIR"/bin/cc
appa
sed -i '4d;3a exec "$@"' "$DIR"/AppRun
part9
