#!/bin/sh
# shellcheck source=../appdwarf
SOURCE=1 . "$(which appdwarf)"
LINK=$(curl https://api.github.com/repos/clangen/musikcube/releases | grep -om1 'http.*_64.*bz2')
unbz
mv "$DIR"/musikcube*/* "$DIR"
appa
appmk
