#!/bin/sh
APP=${0#./mk}
DIR=/tmp/appdwarf/$APP
mkdir "$DIR"
curl http://musl.cc/x86_64-linux-musl-native.tgz | tar xz -C"$DIR"
mv "$DIR"/x86_64-linux-musl-native/* "$DIR"
ln -s gcc "$DIR"/bin/cc
appdwarf -a "$DIR"/AppRun
sed -i '4d;3a exec "$@"' "$DIR"/AppRun
appdwarf "$DIR" "$@"
mv "$DIR".sh "$APP"
rm -rf "$DIR"
