#!/bin/sh
PATH=$(dirname "$(readlink -f "${0}")")/..:$PATH
DIR=/tmp/appdwarf
mkdir -p $DIR
curl http://musl.cc/x86_64-linux-musl-native.tgz | tar xz -C$DIR
mv $DIR/x86_64-linux-musl-native $DIR/musl
ln -s gcc $DIR/musl/bin/cc

cp "$(dirname "$(readlink -f "${0}")")"/../AppRun $DIR/musl
sed -i '4s#"$APPDIR/$ARGV0" ##' $DIR/musl/AppRun

appdwarf $DIR/musl
mv $DIR/musl.sh musl
rm -rf $DIR/musl
