#!/bin/sh
APP=${0#./mk}
DIR=/tmp/appdwarf/$APP
mkdir -p "$DIR"
LINK=$(curl https://nodejs.org/en/download/current/ | grep -m1 linux | cut -d\" -f4)
curl -L "$LINK" | tar xJ -C"$DIR"
mv "$DIR"/node*/* "$DIR"
appdwarf -b "$DIR"/AppRun
appdwarf "$DIR"
mv "$DIR".sh "$APP"
rm -rf "$DIR"
