#!/bin/sh
# shellcheck source=../appdwarf
SOURCE=1 . "$(which appdwarf)"
LINK=https://nodejs.org/dist/latest/
LINK=$LINK$(curl $LINK | grep linux-x64.tar.xz | cut -d\" -f2)
unxz
mv "$DIR"/node*/* "$DIR"
appb
appmk
