#!/bin/sh
. "$(dirname "$0")"/appmk
part0
APP="$1"
sudo pacman -Sw --cachedir "$DIR" "$@"
parallel "tar xf {} -C$DIR" ::: "$DIR"/*.tar.zst
rm -f "$DIR"/*.tar.zst*
appb
sed -i 4s#/lib#/usr/lib#g "$DIR"/AppRun
sed -i 3,5s#/bin#/usr/bin# "$DIR"/AppRun
part9
