#!/bin/sh
PATH=$(dirname "$(readlink -f "${0}")")/..:$PATH
DIR=/tmp/appdwarf/proton
mkdir -p $DIR

LINK="$(curl https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases | grep -om1 http.\*tar.gz)"
curl -L "$LINK" | tar xz -C$DIR
mv $DIR/GE-Proton*/files/* $DIR
rm -rf $DIR/GE-Proton*/

wget -O$DIR/winetricks https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
chmod +x $DIR/winetricks

cat > $DIR/AppRun << 'EOF'
#!/bin/sh
HERE=$(dirname "$(readlink -f "${0}")")

export WINE="${HERE}"/bin/wine
export WINE64="${HERE}"/bin/wine64
export WINESERVER="${HERE}"/bin/wineserver
export WINETRICKS="${HERE}"/winetricks
export DXVK_STATE_CACHE_PATH=~/.cache DXVK_LOG_PATH=none

if [ "$1" = "winetricks" ]; then
	if [ $# -ge 2 ]; then
		shift
		"${WINETRICKS}" "$@"
	else
		"${WINETRICKS}" --help
	fi
else
	"${WINE}" "$@"
	"${WINESERVER}" -w
fi
EOF
chmod +x $DIR/AppRun

appdwarf $DIR "$@"
rm -rf $DIR
mv $DIR.sh proton 
