#!/bin/sh
# shellcheck source=../appdwarf
SOURCE=1 . "$(which appdwarf)"
LINK=$(curl https://www.renpy.org/latest.html | grep 7z | cut -d\" -f2)
un7z renpy.exe
mkdir "$DIR"/lib
mv "$DIR"/renpy-*/lib/py3-linux-x86_64 "$DIR"/renpy-*/lib/python* "$DIR"/lib
mv "$DIR"/renpy-*/renpy* "$DIR"
rm -r "$DIR"/*.exe "$DIR"/renpy-* "$DIR/renpy.app"
ln -s renpy.sh "$DIR/AppRun"
appmk
