#!/bin/sh
# shellcheck source=../appdwarf
SOURCE=1 . "$(which appdwarf)"
ARCH=x86_64-unknown-linux-gnu
LINK=https://static.rust-lang.org/dist/rust-nightly-$ARCH.tar.gz
ungz
"$DIR"/rust-nightly-$ARCH/install.sh --prefix="$DIR" --components=cargo,rustc,rust-std-$ARCH
rm -rf "$DIR"/rust-nightly-$ARCH
appb
appmk
