#!/bin/sh
. "$(dirname "$0")"/appmk
part0
ARCH=x86_64-unknown-linux-gnu
LINK=https://static.rust-lang.org/dist/rust-beta-$ARCH.tar.gz
ungz
"$DIR"/rust-beta-$ARCH/install.sh --prefix="$DIR" --components=cargo,rustc,rust-std-$ARCH
rm -rf "$DIR"/rust-beta-$ARCH
appb
part9
