#!/bin/sh
. "$(dirname "$0")"/appmk
part0
eopkg fc -o "$DIR" signal-desktop
parallel "unzip -op {} install.tar.xz | tar xJf - -C$DIR" ::: "$DIR"/*.eopkg 
ln -s usr/share/signal-desktop/signal-desktop "$DIR"/AppRun
rm "$DIR"/*.eopkg
part9
